export default {
  'expenses': [{
    'id': 1450817381460,
    'description': 'Lunch',
    'amount': 100,
    'category': 'food',
    'account': 'salary',
    'paymentMode': 'debit-card'
  }, {
    'id': 1450846181810,
    'description': 'Jeans',
    'amount': 799,
    'category': 'shopping',
    'account': 'business',
    'paymentMode': 'credit-card'
  }, {
    'id': 1450917382160,
    'description': 'Rent',
    'amount': 4150,
    'category': 'rent',
    'account': 'farming',
    'paymentMode': 'cash'
  }, {
    'id': 1450917382510,
    'description': 'Dinner',
    'amount': 80,
    'category': 'food',
    'account': 'salary',
    'paymentMode': 'cash'
  }, {
    'id': 1451017382860,
    'description': 'Petrol',
    'amount': 500,
    'category': 'fuel',
    'account': 'salary',
    'paymentMode': 'cash'
  }, {
    'id': 1451117382860,
    'description': 'Groceries',
    'amount': 1000,
    'category': 'shopping',
    'account': 'salary',
    'paymentMode': 'credit-card'
  }, {
    'id': 1451291335302,
    'description': 'team lunch',
    'amount': 2000,
    'category': 'food',
    'paymentMode': 'debit-card',
    'account': 'business'
  }, {
    'id': 1451372764033,
    'description': 'Bday Party',
    'amount': 5000,
    'category': 'food',
    'paymentMode': 'credit-card',
    'account': 'business'
  }, {
    'id': 1451375163545,
    'description': 'December Rent',
    'amount': 4150,
    'category': 'rent',
    'paymentMode': 'debit-card',
    'account': 'salary'
  }, {
    'id': 1451375397001,
    'description': 'Memory Card',
    'amount': 600,
    'category': 'shopping',
    'paymentMode': 'debit-card',
    'account': 'business'
  }, {
    'id': 1451461404912,
    'description': 'Helmet',
    'amount': 2000,
    'category': 'shopping',
    'paymentMode': 'cash',
    'account': 'salary'
  }, {
    'id': 1451559405763,
    'description': 'Pulsar',
    'amount': 79000,
    'category': 'shopping',
    'paymentMode': 'credit-card',
    'account': 'business'
  }],
  'accounts': [{
    'name': 'salary',
    'balance': 92170
  }, {
    'name': 'business',
    'balance': 12601
  }, {
    'name': 'farming',
    'balance': 95850
  }]
}
